version: '3.8'

services:
  victim:
    image: docker.io/andrewmichaelsmith/docker-heartbleed
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - /home/seed/Desktop/SR_Project/idk/SR_Project/www:/var/www
      - ./curl_script.sh:/curl_script.sh
    